DROP TABLE PHOTO;
DROP TABLE CUSTOMER_ATTENDS_EVENTS;
DROP TABLE PAYMENT_IS_LINKED_TO_PACKAGE;
DROP TABLE CUSTOMER_TELEPHONE_NUMBERS;
DROP TABLE CUSTOMER_ACQUIRES_PACKAGES;
DROP TABLE MOUNTAIN;
DROP TABLE PAYMENT;
DROP TABLE PACKAGES;
DROP TABLE EVENT;
DROP TABLE EVENT_CATEGORY;
DROP TABLE PLACE;
DROP TABLE CUSTOMER;

